%%{init: {"htmlLabels": false, "flowchart": {"htmlLabels": false}}}%%
erDiagram
    ESTUDIANTE ||--o{ INSCRIPCION : realiza
    INSCRIPCION }o--|| ASIGNATURA : corresponde
    ASIGNATURA ||--o{ PRACTICA : incluye
