%%{init: {"htmlLabels": false, "flowchart": {"htmlLabels": false}}}%%
classDiagram
    class Experimento {
        +string nombre
        +date fecha
        +ejecutar()
        +analizar()
    }
    class Muestra {
        +string tipo
        +float masa
        +preparar()
    }
    Experimento --> Muestra : usa
