###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Álvaro Lozano Murciego y André Sales Mendes (USAL)'
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2025, TeachBooks Project'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx_jupyterbook_latex']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = ''
html_css_files = ['custom.css', 'custom.css', 'custom.css']
html_favicon = ''
html_js_files = ['custom.js', 'custom.js', 'custom.js']
html_logo = '_static/logo.png'
html_sourcelink_suffix = ''
html_static_path = ['_static', '_static']
html_theme = 'sphinx_book_theme'
html_theme_options = {'icon_links': []}
html_title = 'TeachBook (Plantilla Ciencias Químicas)'
latex_engine = 'xelatex'
myst_enable_extensions = ['colon_fence', 'dollarmath', 'linkify']
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'off'
nb_execution_timeout = 30
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = True
